Service:
  type: LoadBalancer
  port: 80
  targetPort: 2368
  nodePort: 30080
Blog:
  name: blog
  labels: blog
  replicas: 1
  image: ghost:2.6-alpine
  imagePullPolicy: Always
  containerPort: 2368
