apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: {{ .Values.Service.type }}
  selector:
    app: {{ .Values.Blog.labels}}
  ports:
  - protocol: TCP
    port: {{ .Values.Service.port }}
    targetPort: {{ .Values.Service.targetPort }}
    {{ if eq .Values.Service.type "NodePort" }}
    nodePort: {{ .Values.Service.nodePort }}
    {{ end }}
